name: Example workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"

jobs:

  clojure:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # It is important to install java before installing clojure tools which needs java
      # exclusions: babashka, clj-kondo and cljstyle
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          # Install just one or all simultaneously
          # The value must indicate a particular version of the tool, or use 'latest'
          # to always provision the latest version
          cli: latest              # Clojure CLI based on tools.deps
          # lein: 2.9.1                  # Leiningen
          # boot: 2.8.3                  # Boot.clj
          # bb: 0.7.8                    # Babashka
          # clj-kondo: 2022.05.31        # Clj-kondo
          # cljfmt: 0.10.2               # cljfmt
          # cljstyle: 0.15.0             # cljstyle
          # cmd-exe-workaround: 'latest' # Replaces `clojure` with `deps.clj` on Windows
          # zprint: 1.2.3                # zprint
          
      # Optional step:

      - name: Execute clojure code
        run: clojure -M:fig:bb
      - name: Push New Compiled Code
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        run: |
          git config --global user.name '@github-ci'
          git config --global user.email 'actions@github.com'
          git add -A
          git commit -m "compiled source"
          git push origin main
      