name: Clojars Snapshot Release

on:
  push:
    branches:
      - main

jobs:
  clojars-snapshot-release:
    name: Clojars Snapshot Release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Java 17 generates class file version 61.0, which is what processing has
      # been compiled with.
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@11.0
        with:
          cli: latest
      - name: Compiling clojurescript 
        run: clojure -M:fig:bb