name: Clojure Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@2.0
      with:
        tools-deps: '1.10.x'  # Specify the version of Clojure tools-deps

    - name: Cache Clojure Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-build-${{ hashFiles('**/deps.edn') }}
        restore-keys: ${{ runner.os }}-build-${{ hashFiles('**/deps.edn') }}-

    - name: Run Clojure Command
      run: clojure -M:fig:bb

    # - name: Commit and Push Changes
    #   run: |
    #     git config --global user.name 'GitHub Actions'
    #     git config --global user.email 'actions@github.com'
    #     git add -A
    #     git diff --staged --quiet && echo "No changes to commit" && exit 0
    #     git commit -m "Automated build commit [skip ci]"
    #     git push
        